// AUTO-GENERATED BY AI SIMULATOR — DO NOT EDIT MANUALLY
// Navigate to /simulator and run "All Personas" to update
export const aiContent: Record<string, { en: string; ru: string }> = {};
export const aiRunMeta = {
  timestamp: '',
  runCount: 0,
  avgScores: {} as Record<string, number>,
  patchedSections: [] as string[],
};
