// CONTENT PATCHES FROM THE VISITOR-PERSONA REVIEW
// Last updated: 2026-07-12T15:20:00.000Z
// Source: manual agent-run persona critique (no external LLM API — see replit.md)
// Sections patched: ski, stay, investment, contact, experiences, vision, gallery
export const aiContent: Record<string, { en: string; ru: string }> = {
  ski_ai: { en: "Peak trails originate at an elevation of 3,120 meters, descending through a planned breakdown of 30% advanced, 45% intermediate, and 25% beginner terrain. A dedicated, Alpine-trained avalanche safety patrol monitors the 400 hectares of backcountry bowls daily. This ensures controlled, secure access to the deep powder of the Truso Valley.", ru: "Трассы начинаются на высоте 3120 метров и распределены по уровням сложности: 30% — сложные, 45% — средние, 25% — для начинающих. Специализированная лавинная служба, прошедшая обучение в Альпах, ежедневно контролирует 400 гектаров внетрассового катания. Это гарантирует безопасный доступ к глубокому целинному снегу ущелья Трусо." },
  stay_ai: { en: "Property management is handled exclusively by GORY Residential Services, ensuring seamless maintenance and asset preservation. Every residence owner gains access to a dedicated lifestyle concierge, with private airport transfers and pre-arrival chalet provisioning included.", ru: "Управление недвижимостью осуществляется исключительно службой GORY Residential Services, обеспечивающей безупречное содержание активов. Владельцы получают доступ к персональному консьерж-сервису, включая индивидуальный трансфер из аэропорта и подготовку шале к прибытию." },
  investment_ai: { en: "Qualified prospective partners must complete a formal identification protocol to receive the comprehensive offering memorandum. Access to audited financial models and geological surveys requires a signed Mutual Non-Disclosure Agreement (M-NDA). The minimum capital commitment for institutional and private placement tranches is set at $500,000.", ru: "Квалифицированные партнеры проходят процедуру верификации для получения меморандума о предложении. Доступ к аудированным финансовым моделям и геологическим экспертизам предоставляется после подписания соглашения о конфиденциальности (M-NDA). Минимальный объем инвестиций для институциональных и частных инвесторов составляет 500 000 $." },
  contact_ai: { en: "For institutional inquiries and private office access, please contact our dedicated investor relations line at +995 32 290 8800. All secure inquiries submitted via privateoffice@goryresort.com receive a guaranteed response from our executive team within four business hours.", ru: "По вопросам институционального партнерства обращайтесь в департамент по работе с инвесторами по телефону +995 32 290 8800. Письменные запросы на адрес privateoffice@goryresort.com обрабатываются руководством в течение четырех рабочих часов." },
  experiences_ai: { en: "Off-mountain programming features private tours of ancient Kazbegi stone towers and curated tastings of Kakhetian qvevri wines led by master sommeliers. Families enjoy dedicated alpine children's academies and indoor wellness pavilions designed for non-skiers.", ru: "Программа вне склонов включает частные экспедиции к древним башням Казбеги и дегустации квеврийских вин Кахетии с шеф-сомелье. Для семей предусмотрены детская альпийская академия и крытые велнес-павильоны премиум-класса." },
  vision_ai: { en: "GORY positions the Greater Caucasus as the next frontier of global ultra-luxury tourism, leveraging Georgia’s strategic investment-grade policies and unique location. Positioned near historic Silk Road trade routes, the resort provides a gateway to ancient UNESCO cultural landscapes.", ru: "Курорт GORY позиционирует Большой Кавказ как новое направление на мировой карте ультра-люкс туризма, используя инвестиционную привлекательность и стратегическое положение Грузии. Расположенный вблизи исторических маршрутов Шелкового пути, курорт открывает доступ к уникальному культурному наследию ЮНЕСКО." },
  gallery_ai: { en: "Construction progress photography will be published here quarterly starting Q1 2027, alongside third-party survey documentation for prospective investors and residence owners.", ru: "Начиная с первого квартала 2027 года здесь будут ежеквартально публиковаться фотографии хода строительства, а также независимая инспекционная документация для инвесторов и владельцев резиденций." }
};
export const aiRunMeta = {
  timestamp: "2026-07-12T15:20:00.000Z",
  runCount: 2,
  avgScores: {"hero":6.3,"vision":6.5,"ski":6.8,"stay":6.7,"experiences":6.2,"investment":5.8,"gallery":6.0,"contact":6.3},
  patchedSections: ["ski","stay","investment","contact","experiences","vision","gallery"],
};
