// AUTO-GENERATED BY AI SIMULATOR — DO NOT EDIT MANUALLY
// Stub: will be overwritten after the first simulator run
export const aiContent: Record<string, { en: string; ru: string }> = {};
export const aiRunMeta = {
  timestamp: '',
  runCount: 0,
  avgScores: {} as Record<string, number>,
  patchedSections: [] as string[],
};
