// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gory-v1-cinematic/Home.tsx": () => import("../components/mockups/gory-v1-cinematic/Home.tsx"),
  "./components/mockups/gory-v1-cinematic/Ski.tsx": () => import("../components/mockups/gory-v1-cinematic/Ski.tsx"),
  "./components/mockups/gory-v1-cinematic/Stay.tsx": () => import("../components/mockups/gory-v1-cinematic/Stay.tsx"),
  "./components/mockups/gory-v2-alpine/Home.tsx": () => import("../components/mockups/gory-v2-alpine/Home.tsx"),
  "./components/mockups/gory-v2-alpine/Ski.tsx": () => import("../components/mockups/gory-v2-alpine/Ski.tsx"),
  "./components/mockups/gory-v2-alpine/Stay.tsx": () => import("../components/mockups/gory-v2-alpine/Stay.tsx"),
  "./components/mockups/gory-v3-terrain/Home.tsx": () => import("../components/mockups/gory-v3-terrain/Home.tsx"),
  "./components/mockups/gory-v3-terrain/Ski.tsx": () => import("../components/mockups/gory-v3-terrain/Ski.tsx"),
  "./components/mockups/gory-v3-terrain/Stay.tsx": () => import("../components/mockups/gory-v3-terrain/Stay.tsx")
};
